admin:
   email_shared: email@localhost
   secret_google: secrets.json
   gdrive_dir: Magento-Backup
   logFile: /backup/logs/bk_grive.log
db:
   
   host: localhost
   user: root
   passwd: magento
   database: magento
   port: 3306
app:
   path: /var/www/html/
   path_exclude: /var/www/html/var/cache
backup:
   db_rotation: 10 
   app_rotation: 10
   storage_local: True
   storage: /storage/
